"""Make order_id nullable in product_reviews

Revision ID: f914b7b3632d
Revises: 532bf38c7c9e
Create Date: 2025-06-02 21:20:37.269367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f914b7b3632d'
down_revision: Union[str, None] = '532bf38c7c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # --- SQLite workaround: recreate table with order_id nullable ---
    from alembic import op
    import sqlalchemy as sa

    # 1. Rename old table
    op.rename_table('product_reviews', 'product_reviews_old')

    # 2. Create new table dengan order_id nullable
    op.create_table(
        'product_reviews',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('product_id', sa.Integer(), sa.ForeignKey('products.id'), nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('order_id', sa.Integer(), sa.ForeignKey('orders.id'), nullable=True),  # nullable=True
        sa.Column('user_name', sa.String(), nullable=False),
        sa.Column('user_profile_picture', sa.String(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=False),
        sa.Column('images', sa.Text(), default="[]"),
        sa.Column('created_at', sa.DateTime(), default=sa.func.now()),
    )

    # 3. Copy data dari tabel lama ke tabel baru
    op.execute("""
        INSERT INTO product_reviews
        (id, product_id, user_id, order_id, user_name, user_profile_picture, rating, comment, images, created_at)
        SELECT id, product_id, user_id, order_id, user_name, user_profile_picture, rating, comment, images, created_at
        FROM product_reviews_old
    """)

    # 4. Hapus tabel lama
    op.drop_table('product_reviews_old')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_reviews', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
